AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to create resources for static SPA hosted using API Gateway

Parameters:
  ApiGatewayStageName:
    Type: String
    Description: The name used for the API Gateway Stage - the first part of the path.
    Default: terminal
  Stage:
    Type: String
    Description: environment
    Default: dev
  Bucket_Name:
    Type: String
    Description: Name of S3 bucket which stores frontend files