###############################################################
# aws cloudformation package
#      --template-file apigw-terminal-app.template.yaml \
#      --region us-east-1 \
#      --output-template-file apigw-terminal-app-package.yaml \
#      --s3-bucket meyers-anton-template-files
# aws cloudformation package --template-file apigw-terminal-app.template.yaml --region us-east-1 --output-template-file apigw-terminal-app-package.yaml --s3-bucket meyers-anton-template-files
###############################################################
# aws cloudformation deploy \
#     --template-file apigw-terminal-app.template.yaml \
#     --stack-name apigw-terminal-app \
#     --profile <your-dev-profile> \
#     --parameter-overrides $(cat deployment-sheet.parameters) \
#     --capabilities CAPABILITY_NAMED_IAM \
#     --region us-east-1
# aws cloudformation deploy --s3-bucket meyers-anton-template-files --template-file apigw-terminal-app-package.yaml --stack-name apigw-terminal-app --parameter-overrides $(cat deployment-sheet.parameters) --capabilities CAPABILITY_NAMED_IAM --region us-east-1 --profile default
###############################################################
# aws cloudformation describe-stack-events --stack-name apigw-terminal-app >> stack_events.json
###############################################################
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Custom Terminal API Application

Parameters:
  ApiGatewayStageName:
    Type: String
    Description: The name used for the API Gateway Stage - the first part of the path.
    Default: terminal
  Stage:
    Type: String
    Description: environment
    Default: dev
  BucketName:
    Type: String
    Description: Name of S3 bucket which stores frontend files
  BucketKey:
    Type: String
    Description: Name of S3 file that renders site
    Default: index.html
  DynamoTableName:
    Type: String
    Description: Name of DynamoDB Table

Globals:
  Function:
    Timeout: 5
    Runtime: python3.9
    Environment:
      Variables:
        LOG_LEVEL: INFO

Resources:

  S3TerminalBucketPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub iam-s3-bucket-policy-${Stage}
      Description: !Sub "Policy to fetch objects from the ${BucketKey} bucket"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub "arn:${AWS::Partition}:s3:::${BucketName}/*"

  APIGatewayPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub iam-api-gateway-policy-${Stage}
      Description: Policy attached to role used to deploy APIGW lambdas
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - execute-api:Invoke
            Resource: !Sub "arn:${AWS::Partition}:execute-api:*:${AWS::AccountId}:*"

  DynamoDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub iam-dynamodb-policy-${Stage}
      Description: Policy attached to role used to deploy APIGW lambdas
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:BatchWriteItem
            Resource: !Sub "arn:${AWS::Partition}:dynamodb:*:${AWS::AccountId}:table/*"

  CloudwatchLogsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub iam-cloudwatch-logs-policy-${Stage}
      Description: Policy attached to role used to deploy APIGW lambdas
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:DescribeLogStreams
              - logs:GetLogEvents
              - logs:FilterLogEvents
              - logs:DescribeLogGroups
              - logs:CreateLogGroup
            Resource: !Sub "arn:${AWS::Partition}:logs:*:${AWS::AccountId}:log-group:*"

  LambdaExecutionRole:
    DependsOn:
      - APIGatewayPolicy
      - DynamoDBPolicy
      - CloudwatchLogsPolicy
      - S3TerminalBucketPolicy
    Type: AWS::IAM::Role
    Properties:
      Description: Role used to deploy APIGW lambdas
      RoleName: !Sub "iam-lambda-basic-execution-role-${Stage}"
      ManagedPolicyArns:
        - !Ref APIGatewayPolicy
        - !Ref DynamoDBPolicy
        - !Ref CloudwatchLogsPolicy
        - !Ref S3TerminalBucketPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  ApiGatewayRole:
    DependsOn:
      - CloudwatchLogsPolicy
      - S3TerminalBucketPolicy
    Type: AWS::IAM::Role
    Properties:
      Description: Role for Api Gateway
      RoleName: !Sub "iam-apigw-terminal-app-${Stage}"
      ManagedPolicyArns:
        - !Ref CloudwatchLogsPolicy
        - !Ref S3TerminalBucketPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action:
              - sts:AssumeRole

  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Sub "${BucketName}-logging"

  WebsiteBucket:
    DependsOn:
      - LoggingBucket
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
      BucketName: !Sub ${BucketName}
      WebsiteConfiguration:
        IndexDocument: index.html
        #ErrorDocument: error.html

  #SampleBucketPolicy:
  #  Type: AWS::S3::BucketPolicy
  #  Properties:
  #    Bucket: !Ref WebsiteBucket
  #    PolicyDocument:
  #      Version: "2012-10-17"
  #      Statement:
  #        - Action:
  #          - s3:GetObject
  #          Effect: Allow
  #          Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"
  #          Principal: "*"
  #          Condition:
  #            StringLike:
  #              "aws:Referer":
  #                - "http://example.com/*"
  #                - "http://example.net/*"

  LexLambda:
    DependsOn:
      - LambdaExecutionRole
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda for LexBot configured to work with terminal ui app
      FunctionName: Lex-Terminal-Bot
      CodeUri: ./functions/Lex-Terminal-Bot
      Handler: main.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/iam-lambda-basic-execution-role-${Stage}

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTableName
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ApiGateway:
    DependsOn:
      - WebsiteBucket
      - LexLambda
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub apigateway-custom-terminal-${Stage}
      Description: Host custom terminal UI and its APIs
      EndpointConfiguration:
        Types:
          - REGIONAL
      Mode: overwrite
      BinaryMediaTypes:
       - "*~1*"
      Body:
        info:
          version: "1.0"
          title: !Ref AWS::StackName
        paths:
          "/":
            get:
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Content-Length:
                      type: string
                    Content-Type:
                      type: string
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: GET
                passthroughBehavior: "when_no_match"
                credentials: !Sub "arn:aws:iam::${AWS::AccountId}:role/iam-apigw-terminal-app-${Stage}"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:s3:path/${BucketName}/${BucketKey}"
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Content-Type: "integration.response.header.Content-Type"
                      method.response.header.Content-Length: "integration.response.header.Content-Length"
          "/lex":
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LexLambda.Arn}/invocations
              responses: {}

  # API Gateway Deployment
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: !Ref ApiGatewayStageName

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ApiGatewayDeployment
      RestApiId: !Ref ApiGateway
      StageName: !Ref ApiGatewayStageName

  # API Gateway permissions
  LexLambdaPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      FunctionName: !GetAtt LexLambda.Arn
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/${ApiGatewayStageName}/GET/lex

Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL